# Generated by Django 3.2.3 on 2021-05-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_postimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='posts',
            new_name='post',
        ),
    ]
